import numpy as np

# Step 1:
# Define knot vector
# Irregular spacing
knots = np.array([0., 0.7, 2.3, 3.])
norder = 4

# repeat first and last element for clamping
tau = np.concatenate([
    np.repeat(knots[0], norder),
    knots[1:-1],
    np.repeat(knots[-1], norder)
])

print("Knot Vector is: ", tau)

# Step 2:
# Calculate matrix `C` using
# De-Boor derivative reduction formula.
# After this step, we have:
# The coefficients of the linear spline!

def deriv_matrix(tau, m):
    N = len(tau) - m   # Why?
    Dm = np.zeros((N + 1, N)) # Why?

    for j in range(N + 1):
        denom = tau[j + m - 1] - tau[j]
        coef = (m - 1)/ denom if denom != 0.0  else 0.0
        if j < N:
            Dm[j, j] += coef # Why?
        if j >= 1:
            Dm[j, j - 1] -= coef # Why?
    
    return Dm

D1 = deriv_matrix(tau, 4)
D2 = deriv_matrix(tau, 3)

print("D1 shape:", D1.shape)   # expect (7, 6): 6 cubic basis fns -> 7 quadratic
assert D1.shape == (7, 6)
print("D2 shape:", D2.shape)   # expect (8, 7): 7 quadratic -> 8 linear
assert D2.shape == (8, 7)

C = D2 @ D1
print("C shape:", C.shape)     # expect (8, 6)
assert C.shape == (8, 6)
print(np.round(C, 4))



# Step 3: 
# Compute `R` using BSplines generated by SciPy

from scipy.interpolate import BSpline
from scipy.integrate import quad

n_basis_order2 = len(tau) - 2   # expect 8

def make_linear_bspline(i, n_basis, tau):
    coef = np.zeros(n_basis)
    coef[i] = 1.0
    return BSpline(tau, coef, k=1, extrapolate=False)

R_mat = np.zeros((n_basis_order2, n_basis_order2))

for p in range(n_basis_order2):
    Bp = make_linear_bspline(p, n_basis_order2, tau)
    for q in range(p, n_basis_order2):  # symmetric
        Bq = make_linear_bspline(q, n_basis_order2, tau)

        def integrand(x):
            vp = Bp(x)
            vq = Bq(x)
            vp = 0.0 if np.isnan(vp) else vp
            vq = 0.0 if np.isnan(vq) else vq
            return vp * vq

        val, _ = quad(integrand, tau[0], tau[-1], limit=200)
        R_mat[p, q] = val
        R_mat[q, p] = val   # symmetric

print("R_mat shape:", R_mat.shape)
print(np.round(R_mat, 6))

Omega_ours = C.T @ R_mat @ C
print("Omega_ours:")
print(np.round(Omega_ours, 6))



# VALIDATION
# use R : Code generated using AI

"""
library(fda)

breaks <- c(0, 0.7, 2.3, 3)
norder <- 4

basisobj <- create.bspline.basis(rangeval = c(0, 3), breaks = breaks, norder = norder)
Omega_R <- bsplinepen(basisobj, Lfdobj = 2)
print(round(Omega_R, 6))
"""
